const links =[
    {
        id:"大前端",
        data:[
            {
                id:"JavaScript",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                    {
                        id:"廖雪峰的JavaScript教程",
                        link:"https://www.liaoxuefeng.com/wiki/1022910821149312"
                    },
                    {
                        id:"JavaScript 备忘清单",
                        link:"https://wangchujiang.com/reference/docs/javascript.html"
                    },
                ]
            },
            {
                id:"HTML",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"CSS",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
        ]
    },
    {
        id:"编程",
        data:[
            {
                id:"python",
                data:[
                    {
                        id:"python",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"java-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"C++-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"设计",
                data:[
                    {
                        id:"Photoshop",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"AI-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"111-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"工具大全",
                data:[
                    {
                        id:"a11",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"a2-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"a3-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
        ]
    },
    {
        id:"设计",
        data:[
            {
                id:"JavaScript",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"HTML",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"CSS",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
        ]
    },
    {
        id:"日常",
        data:[
            {
                id:"JavaScript",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"HTML",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"CSS",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
        ]
    },
    {
        id:"博客",
        data:[
            {
                id:"JavaScript",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"HTML",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
            {
                id:"CSS",
                data:[
                    {
                        id:"现代JavaScript教程",
                        link:"https://zh.javascript.info"
                    },
                    {
                        id:"JavaScript-MDN",
                        link:"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript"
                    },
                    {
                        id:"JavaScript-菜鸟教程",
                        link:"https://www.runoob.com/js/js-tutorial.html"
                    },
                ]
            },
        ]
    },
]

export default links